name: Flutter Games CI

permissions: read-all

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  flutter-tests:
    name: Test Flutter stable on Ubuntu
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11

      - name: Set up Java
        uses: actions/setup-java@387ac29b308b003ca37ba93a6cab5eb57c8f5f93
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@2783a3f08e1baf891508463f8c6653c258246225
        with:
          channel: stable

      - name: Run Flutter CI
        run: ./flutter_ci_script_stable.sh
